### ISSUE TITLE
Mutation filter: Write a basic description

### ISSUE THREAD

**Issue by JonasKellerer** [GenSpectrum/dashboard-components#182]
Write the description shown, when clicking on the ? button.

**Comment by chaoran-chen** [comment]
We can use the same description that we also have for Loculus:

![image](https://github.com/user-attachments/assets/f171f075-9fe8-4e26-96ae-561ebafbeac1)

**Comment by fengelniederhammer** [comment]
The component has the reference genomes available, i.e. we could even generate a tailored description that lists the available segments (or whether it's the special single segmented case) and genes.
