### ISSUE TITLE
Relative Growth Advantage: Improve display of advantage metrics

### ISSUE THREAD

**Issue by fengelniederhammer** [GenSpectrum/dashboard-components#231]
In CoV Spectrum, the growth advantage value is displayed like this:

![grafik](https://github.com/GenSpectrum/dashboards/assets/92720311/5184c3ff-1171-4dfb-abbd-d7d72ce997bd)

Make a suggestion to make the growth advantage value more visible. Currently, the value is displayed quite small below the diagram:
![grafik](https://github.com/GenSpectrum/dashboards/assets/92720311/d7cc0f04-706e-4e18-8010-b5ada4cc877f)
It's the most important value here, it should be easy to see.

**Comment by fengelniederhammer** [comment]
Some suggestions: (don't mind the colors, we should change the default color theme that DaisyUI provides)

![Image](https://github.com/GenSpectrum/dashboards/assets/92720311/c9b7d65a-abdd-4a87-a29c-cab3aed98af6)



![Image](https://github.com/GenSpectrum/dashboards/assets/92720311/c467374e-9594-4eac-ab5e-e4cf51498636)



![Image](https://github.com/GenSpectrum/dashboards/assets/92720311/422724db-a365-4eae-bb37-c5bf740c231f)

**Comment by chaoran-chen** [comment]
What about this?

Large screen:

<img src="https://github.com/GenSpectrum/dashboards/assets/18666552/481e1d7e-ae3c-4daa-b7e8-5c4e0bb73319" width="500" />

Small screen:

<img src="https://github.com/GenSpectrum/dashboards/assets/18666552/af89ea41-1291-42af-999b-86152db95785" width="350" />

```
<div style="
    margin-left: auto;
    margin-right: auto;
    display: flex;
    align-items: flex-end;
    flex-wrap: wrap;
"><span style="color: #606060;">Relative advantage:</span><div><span style="
    font-size: 2rem;
    margin-left: 12px;
">68.96%</span><span style="margin-left: 10px;">(65.79% - 72.14%)</span></div>
</div>
```
