### ISSUE TITLE
Aggregate table: sorting is wrong

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/dashboard-components#270]
The order is wrong:

<img width="1104" alt="image" src="https://github.com/GenSpectrum/dashboards/assets/18666552/5666d92f-b110-478a-9763-bc5886666435">

**Comment by chaoran-chen** [comment]
Ah, on the same page, if we sort by `geo_loc_country` asc. and go to the button, we see:

![image](https://github.com/GenSpectrum/dashboard-components/assets/18666552/27398d21-0d6b-452f-a482-5f607caeb4f4)

It seems that everything above _empty_ is correctly sorted but _emptiness_ breaks further sorting. Is it a Gridjs bug?

**Comment by JonasKellerer** [comment]
I tried to use our "initialSort" feature. There the sorting seems to be fine. So it seems that gridjs has some bug. I'll now try to add a sort function to the fields.

**Comment by chaoran-chen** [comment]
If it's a bug of gridjs, I think that it would be great to report it :)
