### ISSUE TITLE
Remove unknown from prevalence over time line chart

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/dashboard-components#272]
In the line chart, it doesn't make sense to have "Unknown":

![image](https://github.com/GenSpectrum/dashboards/assets/18666552/e2174401-a785-47b5-a75e-99d871973a58)

For the other plots and for the table, it should stay.

**Comment by JonasKellerer** [comment]
@chaoran-chen Could you specify with which data you see this bug? (Essentially the attributes of the prevalence over time element you used)

**Comment by JonasKellerer** [comment]
It can be generated using a query without a date filter. Then LAPIS returns also the null values for the dates (see https://lapis-full-mpox.loculus.org/mpox/sample/aggregated?fields=sample_collection_date). A possible LAPIS filter can be `nextcladePangoLineage%241=JN.1*&nextcladePangoLineage%242=XBB.1*`

Clarification: Don't show unknown for line and bubble plot. For bar plot either remove it, or show unknown at the beginning of the x-axis. Keep the unknown fields for the table.
