### ISSUE TITLE
Deploy storybook to components.genspectrum.org

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/dashboard-components#463]
Currently, the storybook for the components are at https://genspectrum.github.io/dashboard-components/. I think that it would be nice to have it on components.genspectrum.org.

**Comment by fengelniederhammer** [comment]
@chaoran-chen Could you please add a corresponding DNS entry?
https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain

GitHub verifies that the page is reachable on that specific custom domain, so we need the DNS entry first it seems.
