### ISSUE TITLE
Change button description from + to add for mutation filter

### ISSUE THREAD

**Issue by JonasKellerer** [GenSpectrum/dashboard-components#474]
The mutation filter uses a "+" sign to add new mutations to the filter. I have not worked with the filter for some time and forgott, that I had to add them first, so I can filter for them. To make the functionality clearer, I would change the button description to "add".

**Comment by fengelniederhammer** [comment]
We could also make the label configurable? For power users it's maybe good to leave it as a `+`, but for everyone else it might be confusing.

**Comment by anna-parker** [comment]
After discussion we have decided to replace the button with a drop-down similar to in cov-spectrum: https://github.com/GenSpectrum/dashboard-components/issues/482
