### ISSUE TITLE
Mutations over time: crash when no data

### ISSUE THREAD

**Issue by fengelniederhammer** [GenSpectrum/dashboard-components#501]
The component fails when it has a filter that returns no data from LAPIS:
* go to mutations over time / By month story (http://localhost:6006/?path=/story/visualization-mutations-over-time--by-month)
* change lapisFilter.dateFrom to `2025-1-15`

Result:
![grafik](https://github.com/user-attachments/assets/14c38086-2842-4bdf-b34c-c0db4224fc8c)
Browser console:
![grafik](https://github.com/user-attachments/assets/9e21d195-1d6b-4be8-a24e-09c54843b728)

**Comment by JonasKellerer** [comment]
#509 needs to be solved first. Moved to blocked for now.
