### ISSUE TITLE
Add the mutations over time visualization

### ISSUE THREAD

**Issue by fengelniederhammer** [GenSpectrum/dashboard-components#59]
This is what it currently looks like in Co-V-Spectrum:
![grafik](https://github.com/GenSpectrum/dashboards/assets/92720311/050d5960-cdeb-43db-a13a-62a2d246005b)

How closely should we follow that?

**Comment by JonasKellerer** [comment]
Add as a new component with name: gs-mutations-over-time.

Find a way to put the selectors in the toolbar. Put the mutations display in the tab body.
